language: go
sudo: false
go:
  - 1.9.x
  - tip

env:
  - TESTS="-race -v -bench=. -coverprofile=coverage.txt -covermode=atomic"
  - TESTS="-race -v ./..."

script:
  - go test $TESTS

after_success:
  - bash <(curl -s https://codecov.io/bash)
